ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.king250.HttpKt.configureHttp
      - com.king250.RoutingKt.configureRouting
      - com.king250.OssKt.startOssScheduler
oss:
  cname: ${OSS_CNAME}
  region: ${OSS_REGION}
  bucket: ${OSS_BUCKET}
  accessKeyId: ${OSS_ACCESS_KEY_ID}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
